version: "3.9"

services:
    web:
        build: .
        container_name: django
        command: gunicorn news_aggregator.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - redis
    celery:
        build: .
        command: celery -A news_aggregator worker -l INFO
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env
        depends_on:
            - web
            - redis
    redis:
        image: "redis:alpine"
    celery-beat:
        build: .
        command: celery -A news_aggregator beat -l info --pidfile=/tmp/celeryd.pid
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env
        depends_on:
            - redis
    nginx:
        build: ./nginx
        volumes:
            - ./staticfiles:/home/app/web/staticfiles:ro
        ports:
            - 80:80
        depends_on:
            - web
volumes:
    static_volume:
